image:
  repo: docker.io/louislam/uptime-kuma
  tag: "2.0.2"
volume:
  enabled: true
  size: 2Gi
podEnv:
  # Allow being displayed in an <iframe>
  - name: UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN
    value: "1"
livenessProbe:
  enabled: false
readinessProbe:
  enabled: false
resources:
  requests:
    memory: 256Mi
  limits:
    memory: 512Mi
