image:
  repository: docker.io/jellyfin/jellyfin
  tag: "10.11.3"

persistence:
  media:
    size: 2560Gi

resources:
  requests:
    generic.dev/render: 1
  limits:
    generic.dev/render: 1

volumes:
  - name: cache
    persistentVolumeClaim:
      claimName: jellyfin-cache

volumeMounts:
  - name: cache
    mountPath: /cache

deploymentStrategy:
  type: Recreate
